//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotificationService.Database.Queries {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SqlQueries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlQueries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NotificationService.Database.Queries.SqlQueries", typeof(SqlQueries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    n.&quot;Id&quot;,
        ///    n.&quot;ContentKey&quot;,
        ///    n.&quot;Type&quot;,
        ///    n.&quot;DateAdded&quot;
        ///FROM
        ///    &quot;Notifications&quot; as n
        ///WHERE
        ///    n.&quot;UserId&quot; = @UserId AND n.&quot;IsDeleted&quot; IS FALSE;.
        /// </summary>
        internal static string GetNotifications {
            get {
                return ResourceManager.GetString("GetNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    COUNT(n.&quot;Id&quot;)
        ///FROM
        ///    &quot;Notifications&quot; as n
        ///WHERE
        ///    n.&quot;UserId&quot; = @UserId AND n.&quot;IsDeleted&quot; IS FALSE.
        /// </summary>
        internal static string GetNotificationsCount {
            get {
                return ResourceManager.GetString("GetNotificationsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO
        ///    &quot;Notifications&quot;
        ///VALUES (@Id, @ContentKey, @Type, @UserId, @IsDeleted, @Now, @Now).
        /// </summary>
        internal static string InsertNotification {
            get {
                return ResourceManager.GetString("InsertNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE
        ///    &quot;Notifications&quot;
        ///SET
        ///    &quot;IsDeleted&quot; = true
        ///WHERE
        ///    &quot;Id&quot; = @NotificationId.
        /// </summary>
        internal static string SoftDeleteNotification {
            get {
                return ResourceManager.GetString("SoftDeleteNotification", resourceCulture);
            }
        }
    }
}
