//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotificationsService.Database.Queries {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SqlQueries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlQueries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NotificationsService.Database.Queries.SqlQueries", typeof(SqlQueries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    n.&quot;Id&quot;,
        ///    n.&quot;Title&quot;,
        ///    n.&quot;Content&quot;,
        ///    n.&quot;Type&quot;,
        ///    n.&quot;DateAdded&quot;
        ///FROM
        ///    notifications.&quot;Notifications&quot; as n
        ///WHERE
        ///    n.&quot;UserId&quot; = @UserId AND n.&quot;IsDeleted&quot; IS FALSE;.
        /// </summary>
        public static string GetNotifications {
            get {
                return ResourceManager.GetString("GetNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    count(n.&quot;Id&quot;)
        ///FROM
        ///    notifications.&quot;Notifications&quot; as n
        ///WHERE
        ///    n.&quot;UserId&quot; = &apos;@UserId&apos;;.
        /// </summary>
        public static string GetNotificationsCount {
            get {
                return ResourceManager.GetString("GetNotificationsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO
        ///    notifications.&quot;Notifications&quot; (Id, Title, Content, Type, UserId, IsDeleted, DateAdded, DateUpdated)
        ///VALUES
        ///    (@Id, @Title, @Content, @Type, @UserId, @IsDeleted, @DateAdded, @DateUpdated);.
        /// </summary>
        public static string InsertNotification {
            get {
                return ResourceManager.GetString("InsertNotification", resourceCulture);
            }
        }
    }
}
