name: Deploy to Azure
on:
  push:
    branches: [ "main" ]
  release:
    types: [published]
  workflow_dispatch:

jobs:
  push_to_registery:
    name: Push Docker image
    runs-on: ubuntu-latest
    environment: Azure
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: michalmoudry/notifications-service

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./src
          push: true
          tags: michalmoudry/notifications-service:latest
          labels: ${{ steps.meta.outputs.labels }}

  migrate_db:
    name: Migrate database schema
    runs-on: ubuntu-latest
    env:
      DB_SERVER_NAME: ${{ secrets.DB_SERVER_NAME }}
      DB_ADMIN_NAME: ${{ secrets.DB_ADMIN_NAME }}
      DB_ADMIN_PASSWORD: ${{ secrets.DB_ADMIN_PASSWORD }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Pull go-migrate and migrate DB
        run: |
          docker pull migrate/migrate
          docker run -v ./src/NotificationsService/Database/Migrations:/migrations --network host migrate/migrate -path=/migrations/ \
          -database postgres://$DB_ADMIN_NAME:$DB_ADMIN_PASSWORD@$DB_SERVER_NAME:5432/mrf?search_path=notifications up

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [push_to_registery, migrate_db]
    environment: Azure
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Update subscription in app's config file
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "[subscription_id]"
          replace: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          regex: false
          include: "**app_template.yml"

      - name: Deploy Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          imageToDeploy: docker.io/michalmoudry/notifications-service:latest
          resourceGroup: ${{ secrets.AZURE_RESOURCE_GROUP }}
          containerAppEnvironment: microservice-ref-framework-env
          containerAppName: notifications-service
          targetPort: 80
          ingress: external
          yamlConfigPath: ./.azure/app_template.yml

      - name: Enable dapr for a Container App
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az containerapp dapr enable \
              -n user-service \
              -g ${{ secrets.AZURE_RESOURCE_GROUP }} \
              --dapr-app-id notifications-service \
              --dapr-app-protocol http \
              --dapr-app-port 80
